'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        /**
         * Add seed commands here.
         *
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   name: 'John Doe',
         *   isBetaMember: false
         * }], {});
         */
        const articles = [
            {
                title: 'Navigating Legal Risk and Compliance in the Era of AI: A Comprehensive Guide for Indian In-House Counsels',
                description: 'As Artificial Intelligence [AI] continues to advance at an unprecedented pace, it presents both opportunities and challenges for in-house counsels in India. Managing legal risk and ensuring compliance in the realm of AI requires a deep understanding of the intricate legal landscape.',
                authorName: 'Yash Kumar Jha',
                content: null,
                estimateReadTime: '15',
                coverImage: null,
                isActive: false,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Data Privacy Laws in India: DPDP Act 2023 Implementation Guide',
                description: 'A comprehensive analysis of the Digital Personal Data Protection Act 2023 and its implications for businesses operating in India. This guide covers compliance requirements, penalties, and best practices.',
                authorName: 'Priya Sharma',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Corporate Governance Framework for Indian Startups',
                description: 'Essential corporate governance principles and practices that Indian startups must adopt to ensure sustainable growth and investor confidence in the competitive market.',
                authorName: 'Rajesh Gupta',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Intellectual Property Strategy for Tech Companies in India',
                description: 'A strategic approach to intellectual property management for technology companies, covering patents, trademarks, copyrights, and trade secrets in the Indian context.',
                authorName: 'Anitha Reddy',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Contract Negotiation Best Practices for Indian Businesses',
                description: 'Master the art of contract negotiation with proven strategies and techniques specifically tailored for the Indian business environment and legal framework.',
                authorName: 'Vikram Singh',
                content: null,
                estimateReadTime: '7',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Employment Law Updates: New Labor Codes in India',
                description: 'Understanding the impact of the four new labor codes on employment practices, worker rights, and compliance requirements for Indian employers.',
                authorName: 'Meera Iyer',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Cryptocurrency Regulations in India: Current Status and Future Outlook',
                description: 'An in-depth analysis of the evolving regulatory landscape for cryptocurrencies in India, including recent developments and potential future regulations.',
                authorName: 'Arjun Patel',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: false,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Mergers and Acquisitions: Legal Due Diligence Checklist',
                description: 'A comprehensive checklist for conducting legal due diligence in M&A transactions, covering key areas of concern and risk assessment strategies.',
                authorName: 'Kavita Malhotra',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'ESG Compliance for Indian Corporations',
                description: 'Environmental, Social, and Governance (ESG) compliance requirements for Indian corporations, including reporting standards and best practices.',
                authorName: 'Suresh Chandra',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Dispute Resolution Mechanisms in Indian Commercial Law',
                description: 'Exploring various dispute resolution mechanisms available in Indian commercial law, including arbitration, mediation, and litigation strategies.',
                authorName: 'Deepika Nair',
                content: null,
                estimateReadTime: '16',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Cross-Border Tax Implications for Indian Businesses',
                description: 'Understanding the tax implications of cross-border transactions and international business operations for Indian companies.',
                authorName: 'Rohit Agarwal',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Regulatory Compliance for Fintech Companies in India',
                description: 'A comprehensive guide to regulatory compliance requirements for fintech companies operating in India, covering RBI guidelines and emerging regulations.',
                authorName: 'Sneha Kapoor',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Consumer Protection Laws: Rights and Remedies',
                description: 'An overview of consumer protection laws in India, including the Consumer Protection Act 2019 and available remedies for consumer grievances.',
                authorName: 'Amit Bansal',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Digital India Initiative: Legal Framework and Compliance',
                description: 'Understanding the legal framework supporting India\'s Digital India initiative and compliance requirements for digital service providers.',
                authorName: 'Ritu Joshi',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Environmental Law Compliance for Manufacturing Industries',
                description: 'Essential environmental law compliance requirements for manufacturing industries in India, including pollution control and waste management.',
                authorName: 'Manoj Kumar',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Banking Regulations: NPA Management and Recovery',
                description: 'Comprehensive guide to Non-Performing Asset (NPA) management and recovery mechanisms under Indian banking regulations.',
                authorName: 'Nisha Verma',
                content: null,
                estimateReadTime: '15',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Real Estate Regulations: RERA Implementation and Impact',
                description: 'Analysis of the Real Estate Regulation and Development Act (RERA) implementation and its impact on the real estate sector in India.',
                authorName: 'Gaurav Mehta',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Insurance Law Updates: Recent Regulatory Changes',
                description: 'Recent updates and regulatory changes in Indian insurance law, including new guidelines and compliance requirements.',
                authorName: 'Pooja Sinha',
                content: null,
                estimateReadTime: '7',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Corporate Social Responsibility: Legal Obligations and Best Practices',
                description: 'Understanding CSR legal obligations under the Companies Act 2013 and best practices for effective CSR implementation.',
                authorName: 'Kiran Desai',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Competition Law: Anti-Trust Compliance for Indian Companies',
                description: 'A comprehensive guide to competition law compliance and anti-trust regulations for Indian companies under the Competition Act.',
                authorName: 'Ashish Tiwari',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Healthcare Regulations: Medical Device Compliance',
                description: 'Regulatory compliance requirements for medical devices in India, including licensing, quality standards, and safety regulations.',
                authorName: 'Dr. Sunita Rao',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Foreign Exchange Management: FEMA Compliance Guide',
                description: 'Understanding Foreign Exchange Management Act (FEMA) regulations and compliance requirements for businesses and individuals.',
                authorName: 'Rajiv Khanna',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Telecom Regulations: Spectrum Allocation and Licensing',
                description: 'Overview of telecom regulations in India, including spectrum allocation policies and licensing requirements for telecom operators.',
                authorName: 'Vinod Sharma',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Securities Law: Capital Market Regulations and Compliance',
                description: 'Understanding securities law and capital market regulations in India, including SEBI guidelines and compliance requirements.',
                authorName: 'Madhuri Pandit',
                content: null,
                estimateReadTime: '16',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Agricultural Laws: Recent Reforms and Their Impact',
                description: 'Analysis of recent agricultural law reforms in India and their impact on farmers, agribusiness, and the agricultural sector.',
                authorName: 'Ramesh Yadav',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Insolvency and Bankruptcy Code: Recent Amendments',
                description: 'Recent amendments to the Insolvency and Bankruptcy Code (IBC) and their implications for creditors, debtors, and resolution professionals.',
                authorName: 'Sanjay Mishra',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Cyber Security Laws: Data Protection and Privacy',
                description: 'Comprehensive overview of cyber security laws in India, focusing on data protection, privacy rights, and compliance requirements.',
                authorName: 'Neha Agarwal',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Education Law: Regulatory Framework for Educational Institutions',
                description: 'Understanding the regulatory framework governing educational institutions in India, including licensing, accreditation, and compliance requirements.',
                authorName: 'Prof. Indira Devi',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Media and Entertainment Law: Content Regulation and Censorship',
                description: 'Overview of media and entertainment law in India, including content regulation, censorship guidelines, and broadcasting regulations.',
                authorName: 'Tarun Malhotra',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Aviation Law: Regulatory Framework for Airlines and Airports',
                description: 'Understanding the regulatory framework governing aviation in India, including licensing requirements for airlines and airport operations.',
                authorName: 'Captain Mohan Das',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Pharmaceutical Regulations: Drug Approval and Manufacturing',
                description: 'Comprehensive guide to pharmaceutical regulations in India, covering drug approval processes, manufacturing standards, and compliance requirements.',
                authorName: 'Dr. Rakesh Gupta',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Energy Law: Renewable Energy Policies and Regulations',
                description: 'Overview of energy law in India, focusing on renewable energy policies, regulations, and incentives for clean energy projects.',
                authorName: 'Pradeep Singh',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Import-Export Regulations: Trade Policy and Compliance',
                description: 'Understanding import-export regulations and trade policy in India, including customs procedures and compliance requirements.',
                authorName: 'Sunil Aggarwal',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Tax Litigation: Strategies and Best Practices',
                description: 'Effective strategies and best practices for tax litigation in India, including case preparation, documentation, and court procedures.',
                authorName: 'Shweta Jain',
                content: null,
                estimateReadTime: '15',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Corporate Restructuring: Legal and Tax Implications',
                description: 'Comprehensive analysis of legal and tax implications of corporate restructuring in India, including mergers, demergers, and spin-offs.',
                authorName: 'Dinesh Chandra',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'International Trade Law: WTO Compliance and Dispute Resolution',
                description: 'Understanding international trade law, WTO compliance requirements, and dispute resolution mechanisms for Indian businesses.',
                authorName: 'Ankit Saxena',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Constitutional Law: Fundamental Rights and Judicial Review',
                description: 'Analysis of fundamental rights under the Indian Constitution and the role of judicial review in protecting constitutional principles.',
                authorName: 'Justice Retired K.M. Sharma',
                content: null,
                estimateReadTime: '16',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Criminal Law Updates: Recent Amendments and Landmark Judgments',
                description: 'Recent amendments to criminal law in India and analysis of landmark judgments that have shaped the criminal justice system.',
                authorName: 'Advocate Ravi Kumar',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Family Law: Marriage, Divorce, and Property Rights',
                description: 'Comprehensive guide to family law in India, covering marriage laws, divorce procedures, and property rights for different communities.',
                authorName: 'Adv. Kavitha Menon',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Property Law: Land Acquisition and Registration',
                description: 'Understanding property law in India, including land acquisition procedures, registration requirements, and title verification.',
                authorName: 'Mohit Agarwal',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Administrative Law: Government Decision-Making and Judicial Review',
                description: 'Overview of administrative law principles, government decision-making processes, and judicial review of administrative actions.',
                authorName: 'Prof. Rajesh Aggarwal',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Contract Law: Formation, Performance, and Remedies',
                description: 'Fundamental principles of contract law in India, including contract formation, performance obligations, and available remedies for breach.',
                authorName: 'Sameer Joshi',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Tort Law: Negligence and Liability Principles',
                description: 'Understanding tort law in India, including negligence principles, liability concepts, and remedies for tortious conduct.',
                authorName: 'Adv. Priya Bhatt',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Evidence Law: Admissibility and Examination of Witnesses',
                description: 'Comprehensive guide to evidence law in India, covering admissibility rules, examination of witnesses, and documentary evidence.',
                authorName: 'Senior Advocate Mohan Lal',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Arbitration Law: Domestic and International Arbitration',
                description: 'Understanding arbitration law in India, including domestic arbitration procedures and international commercial arbitration.',
                authorName: 'Arbitrator Suresh Patel',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Legal Ethics: Professional Conduct and Disciplinary Proceedings',
                description: 'Overview of legal ethics and professional conduct rules for lawyers in India, including disciplinary proceedings and sanctions.',
                authorName: 'Bar Council Member Ravi Shankar',
                content: null,
                estimateReadTime: '7',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Jurisprudence: Legal Theory and Philosophy',
                description: 'Introduction to jurisprudence and legal theory, exploring different schools of legal thought and their application in Indian law.',
                authorName: 'Prof. Anita Sharma',
                content: null,
                estimateReadTime: '15',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Public Interest Litigation: Access to Justice and Social Reform',
                description: 'Understanding Public Interest Litigation (PIL) as a tool for access to justice and social reform in the Indian legal system.',
                authorName: 'Social Activist Advocate Meera Devi',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Legal Research Methodology: Techniques and Best Practices',
                description: 'Comprehensive guide to legal research methodology, including research techniques, source evaluation, and citation practices.',
                authorName: 'Research Scholar Deepak Gupta',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Alternative Dispute Resolution: Mediation and Conciliation',
                description: 'Overview of alternative dispute resolution mechanisms in India, focusing on mediation and conciliation processes.',
                authorName: 'Mediator Adv. Sunita Rao',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Legal Writing: Drafting Pleadings and Legal Documents',
                description: 'Essential guide to legal writing, including techniques for drafting pleadings, contracts, and other legal documents.',
                authorName: 'Legal Writer Vikash Sharma',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Court Procedures: Civil and Criminal Litigation Process',
                description: 'Step-by-step guide to court procedures in India, covering both civil and criminal litigation processes.',
                authorName: 'Court Master Retired Ram Prasad',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Legal Technology: Digital Transformation in Legal Practice',
                description: 'Exploring the impact of technology on legal practice, including legal tech tools, AI applications, and digital transformation.',
                authorName: 'Legal Tech Expert Rahul Verma',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'International Law: Treaties and Diplomatic Relations',
                description: 'Understanding international law principles, treaty obligations, and diplomatic relations in the context of Indian foreign policy.',
                authorName: 'Diplomat Retired Sushma Patel',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Human Rights Law: Protection and Enforcement Mechanisms',
                description: 'Comprehensive overview of human rights law in India, including protection mechanisms and enforcement procedures.',
                authorName: 'Human Rights Lawyer Arun Kumar',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Women and Law: Gender Justice and Legal Reforms',
                description: 'Analysis of laws relating to women in India, gender justice issues, and recent legal reforms for women\'s rights.',
                authorName: 'Women\'s Rights Advocate Priti Singh',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Child Rights: Protection and Welfare Laws',
                description: 'Understanding child rights and protection laws in India, including child welfare measures and juvenile justice system.',
                authorName: 'Child Rights Expert Dr. Nalini Rao',
                content: null,
                estimateReadTime: '9',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Disability Rights: Legal Framework and Accessibility',
                description: 'Overview of disability rights laws in India, including the Rights of Persons with Disabilities Act and accessibility requirements.',
                authorName: 'Disability Rights Advocate Mohan Das',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Elder Law: Rights and Protection of Senior Citizens',
                description: 'Understanding elder law and rights of senior citizens in India, including maintenance obligations and protection measures.',
                authorName: 'Elder Law Specialist Geeta Sharma',
                content: null,
                estimateReadTime: '8',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Environmental Justice: Climate Change and Legal Responses',
                description: 'Exploring environmental justice issues and legal responses to climate change in India, including green tribunals and environmental litigation.',
                authorName: 'Environmental Lawyer Anil Gupta',
                content: null,
                estimateReadTime: '14',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Consumer Rights: E-commerce and Digital Transactions',
                description: 'Understanding consumer rights in the digital age, including e-commerce regulations and protection in digital transactions.',
                authorName: 'Consumer Rights Advocate Sanjay Mehta',
                content: null,
                estimateReadTime: '10',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Sports Law: Regulations and Governance in Indian Sports',
                description: 'Overview of sports law in India, including governance structures, regulations, and legal issues in sports industry.',
                authorName: 'Sports Law Expert Rajesh Khanna',
                content: null,
                estimateReadTime: '11',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Maritime Law: Shipping and Port Regulations',
                description: 'Understanding maritime law in India, including shipping regulations, port operations, and admiralty jurisdiction.',
                authorName: 'Maritime Lawyer Captain Suresh Rao',
                content: null,
                estimateReadTime: '13',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Space Law: Satellite Technology and Commercial Space Activities',
                description: 'Emerging area of space law in India, covering satellite technology regulations and commercial space activities.',
                authorName: 'Space Law Expert Dr. Kiran Patel',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                title: 'Gaming Law: Online Gaming Regulations and Compliance',
                description: 'Understanding the evolving regulatory landscape for online gaming in India, including compliance requirements and legal challenges.',
                authorName: 'Gaming Law Specialist Arjun Malhotra',
                content: null,
                estimateReadTime: '12',
                coverImage: null,
                isActive: true,
                publishedAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date()
            }
        ]
        await queryInterface.bulkInsert('Articles', articles, {});
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    }
};
